services:
  mongodb:
    image: mongo:7
    container_name: utiliter-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: utiliter

volumes:
  mongodb_data:
